
exclude:
  - ".git"
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Nätet
subtitle: Friluftförskolan
url: "https://natet.hosting.accodeing.com/"
logo: "/assets/img/logo.png"

# Google analytics
# ga_tracking_id: "UA-XXXX-1"
